[package]
name = "duckstruct"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.1"
drop_bomb = "0.1.5"
logos = "0.12.0"
project-root = "0.2.2"
rowan = "0.12.6"
num-derive = "0.3.3"
num-traits = "0.2.14"

[dev-dependencies]
expect-test = "1.0.1"
